packageExtensions:
  babel-loader@*:
    dependencies:
      webpack: '*'
  eslint-config-react-app@*:
    dependencies:
      babel-eslint: '*'
  react-dev-utils@*:
    dependencies:
      typescript: '*'
      webpack: '*'
  react-styleguidist@*:
    dependencies:
      webpack: '*'
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: 'https://github.com/mskelton/yarn-plugin-outdated/raw/main/bundles/@yarnpkg/plugin-outdated.js'

yarnPath: .yarn/releases/yarn-2.4.2.cjs
